export const pokemonList = [
  {
    name: "Bulbasaur",
    evolution: 1,
    evolutionsteps: 3,
    category: "Seed",
    type: ["Grass", "poison"],
    strongAgainst: ["Fighting", "water", "grass", "electric", "fairy"],
    weakAgainst: ["Flying", "fire", "psychic", "ice"],
  },
  {
    name: "Charmander",
    evolution: 1,
    evolutionsteps: 3,
    category: "Lizard",
    type: ["Fire"],
    strongAgainst: ["Bug", "grass", "steel", "fire", "ice", "fairy"],
    weakAgainst: ["Ground", "rock", "water"],
  },
  {
    name: "Squirtle",
    evolution: 1,
    evolutionsteps: 3,
    category: "Tiny turtle",
    type: ["Water"],
    strongAgainst: ["Steel", "fire", "water", "ice"],
    weakAgainst: ["Grass", "electric"],
  },
  {
    name: "Caterpie",
    evolution: 1,
    evolutionsteps: 3,
    category: "Worm",
    type: ["bug"],
    strongAgainst: ["Fighting", "ground", "grass"],
    weakAgainst: ["Flying", "rock", "fire"],
  },
  {
    name: "Weedle",
    evolution: 1,
    evolutionsteps: 3,
    category: "Hairy bug",
    type: ["Bug", "poison"],
    strongAgainst: ["Fighting", "poison", "bug", "grass", "fairy"],
    weakAgainst: ["Fire", "flying", "psychic", "rock"],
  },
  {
    name: "Pidgey",
    evolution: 1,
    evolutionsteps: 3,
    category: "Tiny Bird",
    type: ["Normal", "flying"],
    strongAgainst: ["Bug", "grass"],
    weakAgainst: ["Electric", "ice", "rock"],
  },
  {
    name: "Rattata",
    evolution: 1,
    evolutionsteps: 2,
    category: "Mouse",
    type: ["Normal"],
    strongAgainst: ["Ghost"],
    weakAgainst: ["Fighting"],
  },
  {
    name: "Spearow",
    evolution: 1,
    evolutionsteps: 2,
    category: "Tiny bird",
    type: ["Normal", "flying"],
    strongAgainst: ["Ground", "ghost", "bug", "grass"],
    weakAgainst: ["Rock", "electric", "ice"],
  },
  {
    name: "Ekans",
    evolution: 1,
    evolutionsteps: 2,
    category: "Snake",
    type: ["Poison"],
    strongAgainst: ["Fighting", "poison", "bug", "grass", "fairy"],
    weakAgainst: ["Ground", "psychic"],
  },
  {
    name: "Sandshrew",
    evolution: 1,
    evolutionsteps: 2,
    category: "Mouse",
    type: ["Ground"],
    strongAgainst: ["Electric", "poison", "rock"],
    weakAgainst: ["Water", "grass", "ice"],
  },
  {
    name: "Nidoran♀",
    evolution: 1,
    evolutionsteps: 3,
    category: "Poison pin",
    type: ["Poison"],
    strongAgainst: ["Fighting", "poison", "bug", "grass", "fairy"],
    weakAgainst: ["Ground", "psychic"],
  },
  {
    name: "Nidoran♂",
    evolution: 1,
    evolutionsteps: 3,
    category: "Poison pin",
    type: ["Poison"],
    strongAgainst: ["Fighting", "poison", "bug", "grass", "fairy"],
    weakAgainst: ["Ground", "psychic"],
  },
  {
    name: "Clefairy",
    evolution: 1,
    evolutionsteps: 2,
    category: "Fairy",
    type: ["Fairy"],
    strongAgainst: ["Dragon", "fighting", "bug", "dark"],
    weakAgainst: ["Poison", "steel"],
  },
  {
    name: "Vulpix",
    evolution: 1,
    evolutionsteps: 2,
    category: "Fox",
    type: ["Fire"],
    strongAgainst: ["Bug", "grass", "steel", "fire", "ice", "fairy"],
    weakAgainst: ["Water", "ground", "rock"],
  },
  {
    name: "Jigglypuff",
    evolution: 1,
    evolutionsteps: 2,
    category: "Balloon",
    type: ["Normal", "fairy"],
    strongAgainst: ["Ghost", "dragon", "bug", "dark"],
    weakAgainst: ["Poison", "steel"],
  },
  {
    name: "Zubat",
    evolution: 1,
    evolutionsteps: 2,
    category: "Bat",
    type: ["Poison", "flying"],
    strongAgainst: ["Ground", "fighting", "poison", "bug", "grass", "fairy"],
    weakAgainst: ["Rosck", "electric", "psychic", "ice"],
  },
  {
    name: "Paras",
    evolution: 1,
    evolutionsteps: 2,
    category: "Mushroom",
    type: ["Bug", "grass"],
    strongAgainst: ["Fighting", "ground", "water", "grass", "electric"],
    weakAgainst: ["Flying", "fire", "poison", "rock", "bug", "ice"],
  },
  {
    name: "Venonat",
    evolution: 1,
    evolutionsteps: 2,
    category: "Insect",
    type: ["Bug", "poison"],
    strongAgainst: ["Fighting", "grass", "poison", "bug", "fairy"],
    weakAgainst: ["Flying", "rock", "fire", "psychic"],
  },
];
/******************************************************************************
    {
    name: "Pikachu",
    evolution: 1,
    evolutionsteps: 2,
    category: "Mouse",
    type: ["Electric"],
    strongAgainst: ["Flying", "steel", "electric"],
    weakAgainst: ["Ground"],
  }
  {
    name: "Oddish",
    evolution: 1,
    evolutionsteps: 3,
    category: "Weed",
    type: ["Grass", "poison"],
    strongAgainst: ["Fighting", "water", "grass", "electric", "fairy"],
    weakAgainst: ["Flying", "ice", "fire", "psychic"],
  },
    ******************************************************************************/

/******************************************************************************
Copy-paste empty object for pokemon
    {
    name: ,
    evolution: 1,
    evolutionsteps: ,
    category: ,
    type: [],
    strongAgainst: [],
    weakAgainst: [],
  }
  ******************************************************************************/
